name: Playwright Demo
on: [push, pull_request]
jobs:
  tests_e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: | 
          TEST_EMAIL=${{ secrets.EMAIL }} \
          TEST_PASSWORD=${{ secrets.PASSWORD }} \
          xvfb-run npx playwright test --workers=1
